title: Stackbit Fresh Theme
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: ' Arnav Chavan'
    tagline: Undergraduate Researcher
    profile_img: images/diligent-rosemary.jpeg
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: PUBLICATIONS
        url: /publications
        style: link
      - url: /time-line
        style: link
        label: TIMELINE
      - label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/arnavchavan'
        style: icon
        icon_class: twitter
        new_window: true
      - label: G
        url: 'https://scholar.google.com/citations?user=s4rghcgAAAAJ&hl=en'
        style: button
        icon_class: dev
        new_window: true
      - label: GitHub
        url: 'https://github.com/Arnav0400'
        style: icon
        icon_class: github
        new_window: true
      - label: K
        style: link
        icon_class: dev
        new_window: false
        no_follow: false
        type: action
        url: 'https://www.kaggle.com/carnav0400'
      - label: LinkedIn
        url: 'https://www.linkedin.com/arnav0400'
        style: icon
        icon_class: linkedin
        new_window: true
  footer:
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=fresh&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://personal-5fb50.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
